// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEurwUviEfLuCn35MW6500i6P9pnk6Ajw',
    appId: '1:179971767232:web:13a371187ab2ea96c0e625',
    messagingSenderId: '179971767232',
    projectId: 'coffeeproject-c98b2',
    authDomain: 'coffeeproject-c98b2.firebaseapp.com',
    storageBucket: 'coffeeproject-c98b2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAf_YmS1os1Yt0YaIhFHBmT44UuyEZ4e8',
    appId: '1:179971767232:android:1f12833f8ab4269fc0e625',
    messagingSenderId: '179971767232',
    projectId: 'coffeeproject-c98b2',
    storageBucket: 'coffeeproject-c98b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6f8cJTVo1Bo2v7JpuZVZU5MruV_VHlxs',
    appId: '1:179971767232:ios:6d0ad3b8457bda9dc0e625',
    messagingSenderId: '179971767232',
    projectId: 'coffeeproject-c98b2',
    storageBucket: 'coffeeproject-c98b2.appspot.com',
    iosBundleId: 'com.example.coffee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6f8cJTVo1Bo2v7JpuZVZU5MruV_VHlxs',
    appId: '1:179971767232:ios:6d0ad3b8457bda9dc0e625',
    messagingSenderId: '179971767232',
    projectId: 'coffeeproject-c98b2',
    storageBucket: 'coffeeproject-c98b2.appspot.com',
    iosBundleId: 'com.example.coffee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEurwUviEfLuCn35MW6500i6P9pnk6Ajw',
    appId: '1:179971767232:web:a97f167d36f4a73bc0e625',
    messagingSenderId: '179971767232',
    projectId: 'coffeeproject-c98b2',
    authDomain: 'coffeeproject-c98b2.firebaseapp.com',
    storageBucket: 'coffeeproject-c98b2.appspot.com',
  );
}
